name: Auto-build HTML files

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - working
  schedule:
    - cron: '50 22 * * *'  # Runs at 10:50 PM UTC every day

jobs:
  call-build-site:
    uses: comic-git/comic_git_engine/.github/workflows/build_site.yaml@v1
