name: Auto-build HTML files

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - working
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 AM UTC every day

jobs:
  call-build-site:
    uses: ryanvilbrandt/comic_git_engine/.github/workflows/build_site.yaml@v1
